### ISSUE TITLE
pyyaml is not installed with clias

### ISSUE THREAD

**Issue by kj-9** [kj-9/clias#1]
```
❯ uv tool install clias
Resolved 4 packages in 650ms
Prepared 2 packages in 60ms
Installed 4 packages in 5ms
 + clias==0.1.0a0
 + click==8.1.7
 + jinja2==3.1.4
 + markupsafe==3.0.2
Installed 1 executable: clias

❯ clias
Traceback (most recent call last):
  File "/Users/kh03/.local/bin/clias", line 5, in <module>
    from clias.cli import cli
  File "/Users/kh03/.local/share/uv/tools/clias/lib/python3.13/site-packages/clias/cli.py", line 8, in <module>
    import yaml  # type: ignore
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'yaml'
```

**Comment by kj-9** [comment]
released with `0.1.0a1`, now works
```
❯ uv tool install -U clias
Resolved 5 packages in 338ms
Prepared 2 packages in 184ms
Uninstalled 1 package in 1ms
Installed 2 packages in 6ms
 - clias==0.1.0a0
 + clias==0.1.0a1
 + pyyaml==6.0.2
Installed 1 executable: clias

❯ clias                   
Usage: clias [OPTIONS] COMMAND [ARGS]...

  Turn shell script into cli command

Options:
  -d, --dryrun  dry run mode, only show the rendered command
  --version     Show the version and exit.
  --help        Show this message and exit.

Commands:
  info  Show the clias config file path to be loaded
```
